# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e4cebddc21f1b10ff8d489e98d8c4f577d219ad61f2c35ab93d57e4f1503e29df653d529aeee9a62084ce03c9ab7973450ad7fccb30a0f147dd47eccfc5f971

test:
  secret_key_base: f480dd4d7042af7b548b7f59163a9e1f31dc7efc4e009b21e6a1b89ba34c62e9121455fd6aab6dd8662d8744b7357253261f53fe5e7c35cb1b218d056670feb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
